### ISSUE TITLE
No method to 'unslug' a string

### ISSUE THREAD

**Issue by mruiz42** [Trott/slug#188]
This may be a feature suggestion, or I may be missing something entirely.
There should be a way to reverse the slug method and revert back to the string before it has been made into a slug.
Example:
```js

const myStr = "Hello World!";  // Hello World!
const mySlug = slug(myStr);   // hello-world
...
console.log(unslug(mySlug));  // out: hello world
```

Although, I see that there may be some cases where data is lost in translation such as the capital letters and exclamation point. There is no way to tell what the previous string was before, but if you already are storing strings in all lower case with no capital letters it may be useful to have a method to revert any changes the `slug()` method does. But it must be noted that it is not fully reliable in all cases. 

Let me know what you think.

**Comment by mruiz42** [comment]
> What is the use case for this?

if you have a url of type view/:category/item that lists items by category
and you want to narrow search results by `:category`, so you pass to backend
"test-category" using the backend url `/search/:category` 
However, since it is stored in database as "test category" You might have to deslug the search parameter in the url.

**Comment by Trott** [comment]
In that situation, I'd be inclined to use `searchTerms.replace(/-/g, ' ')` to accomplish what you want. What are the downsides (if any) to that approach?

**Comment by mruiz42** [comment]
Yes, that is also the approach I took but I was wondering if there were any more cases where it is more complicated than replacing dashes to unslug a string. Basically, without knowing how the slug module works on a deeper level or for more complicated conversions, would `.replace()` be sufficient for most use cases?

**Comment by Trott** [comment]
> Yes, that is also the approach I took but I was wondering if there were any more cases where it is more complicated than replacing dashes to unslug a string. Basically, without knowing how the slug module works on a deeper level or for more complicated conversions, would `.replace()` be sufficient for most use cases?

I would expect `.replace()` to be sufficient for most cases, and an easier-to-modify solution for the cases where it is not sufficient.
