### ISSUE TITLE
Can't keep _ in slug, (eg. by adding _ to charmap)

### ISSUE THREAD

**Issue by stefan1010** [Trott/slug#198]
Seems like _ is always removed. There is no "ignore characters"-option as well, so I dont see how fix it in v4. It worked in 2.1.1

**Comment by Trott** [comment]
Easiest way to restore the old behavior is to specify `rfc3986` as the mode:

```console
> slug('COME_ON fhqwhgads!', { mode: 'rfc3986' })
'come_on-fhqwhgads'
> 
```

While I hope that works for you, it should indeed be more intuitive than that. dding `_` to the charmap should preserve it. (Or at least it should warn you if it's going to have no effect.) Let's keep this open as a bug that needs fixing.

**Comment by Trott** [comment]
Version 4.0.4, which was just published a minute ago or so, will honor `slug.charmap['_'] = '_'` and will not strip out the `_` character that results.
