### ISSUE TITLE
🐛 `-` dash instances are omitted when `replacement` is set to `_` underscore.

### ISSUE THREAD

**Issue by A-Tokyo** [Trott/slug#289]
When providing the replacement as `_` the `-` instances are wrongfully omitted.

```js
slug('arabic-english translator') // "arabic-english-translator"
slug('arabic-english translator', { replacement: '_' }) // "arabicenglish_translator" (this is wrong, should be "arabic-english_translator")
```

expected behavior:
```js
slug('arabic-english translator', { replacement: '_' }) // "arabic_english_translator"
```

**Comment by Trott** [comment]
All non-space punctuation is removed.

If you want to preserve a character, it needs to exist in the charmap:

```js
slug.charmap['-'] = '-';
```

**Comment by Trott** [comment]
I don't think this is right. If you specify that you want your lone non-alphanumeric character to be `_`, then treating `-` as a preserved character is a bug. (We don't preserve `_` in the default situation, for example.) I could see *maybe* arguing that certain symbols (`-`, `_`, and a handful of others) be converted to the replacement character along with spaces. But preserving them seems like a bug to me.

**Comment by Trott** [comment]
Although what you are asking for *is* the behavior of `slugify()`. It preserves `-` and `_` by default.  That seems sensible to me given `slugify`'s more batteries-included approach (where it slugs `<` as `less` and so on). But `slug`'s minimal approach would seem to align better with removing those characters (like it does now) or perhaps converting them to the replacement character.

@simov

**Comment by A-Tokyo** [comment]
@Trott I updated the example:

It's now

```
slug('arabic-english translator', { replacement: '_' }) // "arabic-english_translator"
```
