### ISSUE TITLE
Playground?

### ISSUE THREAD

**Issue by rauschma** [Trott/slug#349]
It’d be nice if slug could be tried out without installing it. Two options are:

* A web page (a “playground”) hosted via GitHub pages.
* A `"bin"` script that can be executed via npx.

**Comment by Trott** [comment]
We should probably do both of those options.

**Comment by Trott** [comment]
Barest of bare-bones playground PR: https://github.com/Trott/slug/pull/350

**Comment by Trott** [comment]
Beneficial side-effect to having set up the playground is that now users can run the tests in their browser by going to https://trott.github.io/slug/test/index.html.

**Comment by Trott** [comment]
Barest of bare-bones CLI PR: https://github.com/Trott/slug/pull/351

**Comment by Trott** [comment]
Do this minimal implementations meet your needs, at least for now? Or do you have the need to be able to specify options?

**Comment by rauschma** [comment]
This looks good, thank you!
