### ISSUE TITLE
Greek theta incorrectly maps to 8

### ISSUE THREAD

**Issue by colinbate** [Trott/slug#353]
I'm not sure if this was a conscious decision based on appearance, and I am not Greek and not an expert, but I do have some Greek content, and I believe that the Greek letter theta (Θ) would be best transliterated to `Th`. With the lowercase θ being `th`.

**Comment by Trott** [comment]
Yes, that certainly seems like a suboptimal choice.

**Comment by Trott** [comment]
Fixed in slug@8.2.2. Thanks for the bug report.
