### ISSUE TITLE
Custom character map replacement changes uppercase characters to lowercase

### ISSUE THREAD

**Issue by neilmahaseth** [Trott/slug#409]
I was trying to replace a Unicode character with some uppercase characters. But if the lowercase mode is toggled on, it also changes the character map replacement to lowercase. 
 
For example 
slug.extend({ "’": "%25E2%2580%2599" });

changes to %25e2%2580%2599

Anyway to maintain the uppercase in character map replacement without toggling the lowercase mode?

**Comment by Trott** [comment]
> Anyway to maintain the uppercase in character map replacement without toggling the lowercase mode?

No. If you have `lower` set to `true` (the default), then `slug` will not return uppercase letters.
