### ISSUE TITLE
Dash get deleted after I use underscore as space replacement

### ISSUE THREAD

**Issue by GhassenRjab** [Trott/slug#413]
Hey,

I use `slug@8.2.3`.
If I use an underscore as a space replacement, dashes get deleted.

Here is an example:

```javascript
import slug from 'slug';

const input = 'My telephone-number';
const output = slug(input, '_');
// output = my_telephonenumber and not my_telephone-number
```

**Comment by Trott** [comment]
All non-alphanumberic characters get deleted by default.

If you want to preserve a character (such as dashes), the easiest way is probably to add it to the `charmap`:

```js
import slug from 'slug';

slug.charmap['-'] = '-';

const input = 'My telephone-number';
const output = slug(input, '_');
// output is 'my_telephone-number'
```
