### ISSUE TITLE
Apostrophes are removed

### ISSUE THREAD

**Issue by Al-phonsio** [Trott/slug#437]
Apostrophes are removed. For example : "I'm lucky" is expected to become "i-m-lucky", bug it produces "im-lucky".

Maybe I can solve this problem with options ? If yes, I didn't find how.

**Comment by Trott** [comment]
This is not a bug. The module removes all punctuation.

**Comment by Al-phonsio** [comment]
OK, maybe in English, it sounds OK. But in French (at least) I think apostrophes should be replaced by hyphens. Is there a way to solve this problem ? I'm ready to contribute if you suggest me where to start. 
--- or ---
Is there a way to add a custom array of characters without removing/replacing the default charmap?
